apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-auth
  template:
    metadata:
      labels:
        app: be-auth
    spec:
      containers:
        - name: be-auth
          image: claudiocidade/be-auth